### ISSUE TITLE
Clingo `Module` not loaded after upgrading emscripten to 3.1.56

### ISSUE THREAD

**Issue by T0nyX1ang** [domoritz/clingo-wasm#412]
Hi, I find another issue which causes the Clingo WASM itself failing to load.

Firstly, when I try to `init` the WASM file, and get the following message:
```text
c54bf20d-d16a-4c94-90fb-41e9f9bf83a8:1 Uncaught (in promise) TypeError: t(...) is not a function
    at s.<anonymous> (c54bf20d-d16a-4c94-90fb-41e9f9bf83a8:1:48190)
    at Generator.next (<anonymous>)
    at c54bf20d-d16a-4c94-90fb-41e9f9bf83a8:1:47377
    at new Promise (<anonymous>)
    at n (c54bf20d-d16a-4c94-90fb-41e9f9bf83a8:1:47122)
    at s.init (c54bf20d-d16a-4c94-90fb-41e9f9bf83a8:1:47765)
    at c54bf20d-d16a-4c94-90fb-41e9f9bf83a8:1:47632
    at Generator.next (<anonymous>)
    at c54bf20d-d16a-4c94-90fb-41e9f9bf83a8:1:47377
    at new Promise (<anonymous>)
```

I try to pinpoint the problem to earlier commits, and find that the code cannot be run after commit 916acd1 and d073014, where
- 916acd1 updates the wasm file
- d073014 claims to fix the import issue

After comparing the former version with the current version (with some `console.log`), I find that the `Module` is not loaded in the client side. In detail, in the following blocks:
```js
      if (Module) {
        console.log("Module is defined");
        this.clingo = await Module(params);
      } else {
        // for Node
        console.log("Module is not defined");
        this.clingo = await require("./clingo")(params);
      }
```

The code will directly go into the `else` branch which is not intended. In the contract, the codes before 916acd1 can normally go into the `Module` branch.

P.S. The codes in #410 can run normally in the previous version.

**Comment by T0nyX1ang** [comment]
I investigate further into that problem, and download the emsdk `v3.1.18` to have a check. The outcomes are good.

So the problem should be somewhere with a breaking change in `emscripten` that causes the issue. It seems like a downgrade of   `emscripten` maybe a possible fix for this issue.

**Comment by T0nyX1ang** [comment]
Some breaking changes are included in `v3.1.40` of `emscripten`. The changelogs are:

- The `_emscripten_out()`, `_emscripten_err()` and `_emscripten_dbg()` functions declared in emscripten/console.h no longer have the underscore prefix and are now documented.

Not getting the key point now :(

**Comment by T0nyX1ang** [comment]
The problem is that:
- 'Clingo` can run on `emscripten==3.1.39`
- `Clingo` can't run on `emscripten==3.1.40`

But I don't know why this happens. The changelog seems not be the reason. Maybe there are some flags missing.

**Comment by T0nyX1ang** [comment]
The new problem is that:

- `Clingo` can run on `emscripten==3.1.44`
- `Clingo` can't run on `emscripten==3.1.45`

In the `v3.1.45`, the generated `Module` structure is changed, which lead to the main problem.

> For the reference, these are the official changelogs from `emscripten`:
> - The function used to add symbols the JS library has been renamed from mergeInto, to the more specific addToLibrary. This new function does not require the passing of LibraryManager.library as a first argument. The old mergeInto continues to exist for backwards compat.
> - The --log_html option was removed from emrun. This option was already not working with python3.8 or above so we hope is safe to say that nobody was relying on it.

**Comment by T0nyX1ang** [comment]
I have made a PR in #413, the issue is resolved in a new version built with a Linux VM.
